### ISSUE TITLE
Investigate possibility of tweaking Logblock settings on P

### ISSUE THREAD

**Issue by tompreuss** [NerdNu/NerdBugs#133]
The padmins are interested in learning more about the current configuration of Logblock on P with the intention of tweaking the settings for the length of certain blocks stored in the database.

The current config and information about the size of the database would be helpful.

**Comment by totemo** [comment]
```
clearlog:
  enableAutoClearLog: true
  auto:
  - world "world" before 7 days block sand gravel dirt stone all
  - world "world" before 21 days all
  dumpDeletedLog: false
  autoClearLogDelay: 6h
```

More information about these parameters can be found here: https://github.com/LogBlock/LogBlock/wiki/Configuration

"All listed lines will be used as params for auto clearlog commands."
From the looks of it, matching records are deleted every 6 hours.

It will take a little bit more work to get information on the database size.
